services:
  auth-api:
    network_mode: host
    environment:
      DATA_API_URL: http://localhost:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      INTERNAL_TOKEN: secret-win-win-token
  data-api:
    network_mode: host
  postgres:

    network_mode: host
